### PR TITLE
Replace the manual tool to restore from an older version by an automa…

### PR DESCRIPTION
**Pull request by mhugo**
…tic one

### CODE REVIEW

**Comment by haubourg** [comment]
Ok, it works..
testing with real project from 2.6.1. I have an issue on project load. See stack trace below.
When it fails it lets qgis with rendering frozen, we need a "try-except" somewhere to fallback in a working state. 

```python
AttributeError: 'NoneType' object has no attribute 'authid' 
Traceback (most recent call last):
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 239, in on_project_open
    self.layer, self.parameters = self.load_from_project()
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 228, in load_from_project
    return self.load_from_layer(l)
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 315, in load_from_layer
    layer = self.apply_mask_parameters(layer, parameters, dest_crs = None, poly = None, name = layer.name(), keep_layer = False)
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 488, in apply_mask_parameters
    nlayer = self.create_layer( parameters, mask_name, is_mem, dest_crs, layer_style )
  File "W:\GIT_DEPOTS\mask\mask\aeag_mask.py", line 660, in create_layer
    layer = QgsVectorLayer("MultiPolygon?crs=%s" % dest_crs.authid(), name, "memory")
AttributeError: 'NoneType' object has no attribute 'authid'
```

I don't get what's wrong, here is the qgs definition for that mask layer:
```xml
  <maplayer minimumScale="0" maximumScale="1e+08" simplifyDrawingHints="1" minLabelScale="0" maxLabelScale="1e+08" simplifyDrawingTol="1" geometry="Polygon" simplifyMaxScale="10000" type="vector" hasScaleBasedVisibilityFlag="0" simplifyLocal="1" scaleBasedLabelVisibilityFlag="0">
            <id>Mask20141105111113674</id>
            <datasource>MultiPolygon?crs=EPSG:2154</datasource>
            <title></title>
            <abstract></abstract>
            <keywordList>
                <value></value>
            </keywordList>
            <layername>Mask</layername>
            <srs>
                <spatialrefsys>
                    <proj4>+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs</proj4>
                    <srsid>145</srsid>
                    <srid>2154</srid>
                    <authid>EPSG:2154</authid>
                    <description>RGF93 / Lambert-93</description>
                    <projectionacronym>lcc</projectionacronym>
                    <ellipsoidacronym>GRS80</ellipsoidacronym>
                    <geographicflag>false</geographicflag>
                </spatialrefsys>
            </srs>
```

**Comment by mhugo** [comment]
I prefer not to hide errors. Can you share the layer (mldata ?)

**Comment by haubourg** [comment]
I didn't mean to hide the error but to catch it, raise it qith qmessagelog + qmessagebar and handle coming back to a correct qgis state. 
I work on a shared version of the project now.

**Comment by haubourg** [comment]
[test.ZIP](https://github.com/aeag/mask/files/57863/test.ZIP)
here is the faulty project with only the mask layer + .mldata. All other layers were removed
Memory layer v3.5 and 3.6 tested > same error.

**Comment by mhugo** [comment]
The main problem comes apparently from MemoryLayerSaver which is loaded *after* mask. So when mask tries to access the layer, there is nothing in here yet.

**Pull request merged**
