### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by mhugo**
* Fix atlas geometry access for QGIS 2.12
* Add an option to restore mask parameters from a layer (to restore parameters from a older version)
* Add doc for function expressions (with fr translations)

### CODE REVIEW

**Comment by haubourg** [comment]
Option to restore parameters from layers does not seem to work. 
I create a mask using v1.4  + qgis 2.12 and mask button remain greyed out.
Atlas works OK with a newly created mask
Doc is OK

**Comment by mhugo** [comment]
I've tested the option to restore with both a shapefile and a memory layer (with memory layer saver).
From qgis 2.12 + mask 1.4 => create a mask, save the project.
Open it in qgis 2.12 + mask master => select the mask layer and call "restore the mask parameters".
Do you have any errors reported ?

**Comment by haubourg** [comment]
Hi, I didn't get that this restore function need to be triggered manually. Is there a reason why it can be done automatically? users won't use a manual function hidden in menus

**Comment by mhugo** [comment]
The storage of parameters changed. They were stored in the mask layer and now they are stored in the project settings.
I can add a way to automatically extract mask parameters if a layer is called Mask ?

**Comment by haubourg** [comment]
If you can do that, that would be great. Users already know that they should not rename mask layer if they want it to be "active".

**Pull request merged**
